TripLog/Controllers/HomeController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using TripLog.Models;
using TripLogDaAL.DAL;
using TripLogDaAL.DBContext;


namespace TripLog.Controllers
{
    public class HomeController : Controller
    {
        private readonly TripDbContext _context;
        public HomeController(TripDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            TripDAL dal = new TripDAL(_context);
            var trips = dal.GetAllTrips();
            return View(trips);
        }

        public IActionResult Delete(int TripId)
        {
            TripDAL dal = new TripDAL(_context);
            bool success = dal.DeleteTrip(TripId);
            if (success)
                TempData["message"] = "Trip deleted successfully";
            else
                TempData["message"] = "DB Error : Failed to delete trip. Please try agian";

            return RedirectToAction("Index");
        }

    }
}

TripLog/Controllers/TripController.cs
using System;
using System.Runtime.InteropServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using TripLog.Models;
using TripLogDaAL.DAL;
using TripLogDaAL.DBContext;
using TripLogDaAL.Entities;

namespace TripLog.Controllers
{
    public class TripController : Controller
    {
        private readonly TripDbContext _context;
        public TripController(TripDbContext context)
        {
            _context = context;
        }
        public RedirectToActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public ViewResult Add(string id = "")
        {
            var vm = new TripViewModel();
            TripDAL dal = new TripDAL(_context);
            vm.Destinations = dal.GetAllDestinations();
            vm.Accommodations = dal.GetAllAccommodations();
            vm.Activities = dal.GetAllActivity();   
            /********************************************************************************************
            * need to pass Accommodation value, or Destination value (depending on page number and 
            * Accommodation value), to by view. 
            * 
            * Accommodation is an optional value - don't need it to persist after being read if it's null.
            * So, do straight read, and if it's not null, use Keep() method to make sure it persists.
            * 
            * Destination is a a required value - always need it to persist after being read. 
            * So, use Peek() method to read it and make sure it persists.
            *********************************************************************************************/
               
            if (id.ToLower() == "page3")
            {
                vm.PageNumber = 3;
                vm.trip = new Trip
                {
                    DestinationId = (int)TempData.Peek(nameof(Trip.DestinationId)),
                    AccommodationId = (int)TempData.Peek(nameof(Trip.AccommodationId)),
                    StartDate = (DateTime)TempData.Peek(nameof(Trip.StartDate)),
                    EndDate = (DateTime)TempData.Peek(nameof(Trip.EndDate)),
                };
                vm.SelectedDestinationName = TempData.Peek(nameof(TripViewModel.SelectedDestinationName)).ToString();
                return View("Add3", vm);
            }
            else 
            {
                vm.PageNumber = 1;
                if (vm.Destinations != null && vm.Destinations.Any())
                {
                    vm.SelectedDestinationName = vm.Destinations[0].DestinationName;
                }
                return View("Add1", vm);
            }      
        }
            
        [HttpPost]
        public IActionResult Add(TripViewModel vm)
        {
            TripDAL dal = new TripDAL(_context);
            if (vm.PageNumber == 1)
            {
                if (ModelState.IsValid) // only page 1 has required data
                {
                    /***************************************************
                    * Store data in TempData and redirect (PRG pattern)
                    ****************************************************/
                    TempData[nameof(Trip.AccommodationId)] = vm.trip.AccommodationId;
                    TempData[nameof(Trip.DestinationId)] = vm.trip.DestinationId;
                    TempData[nameof(Trip.StartDate)] = vm.trip.StartDate;
                    TempData[nameof(Trip.EndDate)] = vm.trip.EndDate;
                    var selectedItem = dal.GetAllDestinations().Find(p => p.DestinationId == vm.trip.DestinationId);
                    TempData[nameof(TripViewModel.SelectedDestinationName)] = selectedItem?.DestinationName;
                    
                    return RedirectToAction("Add", new { id = "Page3" });
                }
                else
                {
                    TempData["message"] = "Enter Valid inputs";
                    return RedirectToAction("Add");
                }
            }
            else if (vm.PageNumber == 3)
            {
                /***************************************************
                    *  Store data in TempData and redirect (PRG pattern)
                ****************************************************/
                

                if (vm.trip != null)
                {
                    bool success = dal.AddTrip(vm.trip);
                    if (success)
                    {
                        TempData["message"] = $"The Following Trip to {TempData.Peek(nameof(TripViewModel.SelectedDestinationName))} has been added.";
                    }
                    else
                    {
                        TempData["message"] = $"Database Error : The Following Trip to {TempData.Peek(nameof(TripViewModel.SelectedDestinationName)).ToString()} has been added.";
                    }
                }
                else
                {
                    TempData["message"] = $"Failed to add trip : {TempData.Peek(nameof(TripViewModel.SelectedDestinationName)).ToString()}";
                }
                
                
           
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        public RedirectToActionResult Cancel()
        {
            TempData.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

TripLog/Views/Home/Index.cshtml
@using TripLogDaAL.Entities
@model IEnumerable<TripLogDaAL.Entities.Trip>

@{
    ViewBag.Title = "My Trip Log";
}

<a asp-action="Add" asp-controller="Trip" class="btn btn-outline-dark"><b>Add Trip</b></a>
@if (Model.Count() != 0)
{
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Destination</th>
                <th>Start Date</th>
                <th>End Date</th>
                <th>Accommodations</th>
                <th>Things To Do</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (Trip trip in Model)
            {
                <tr>
                    <td>@trip.Destination.DestinationName</td>
                    <td>@trip.StartDate.ToShortDateString()</td>
                    <td>@trip.EndDate.ToShortDateString()</td>
                    <td>
                        @if (trip.Accommodation != null)
                        {
                            <div>@trip.Accommodation.AccommodationName</div>
                            @if (!string.IsNullOrEmpty(trip.Accommodation.AccommodationPhone))
                            {
                                <div>Phone: @trip.Accommodation.AccommodationPhone</div>
                            }
                            @if (!string.IsNullOrEmpty(trip.Accommodation.AccommodationEmail))
                            {
                                <div>Email: @trip.Accommodation.AccommodationEmail</div>
                            }
                        }
                    </td>
                    <td>
                       
                        @if (trip.TripActivities != null)
                        {
                            @foreach (TripActivity ta in trip.TripActivities)
                            {
                                @if (ta.Activity != null)
                                {
                                    <div>@ta.Activity.ActivityName</div>
                                }
                            }
                        }
                        
                    </td>
                    <td>
                        <div><a asp-all-route-data="@(new Dictionary<string, string> { { "tripId", trip.TripId.ToString()} })"  asp-action="Delete" asp-controller="Home" class="btn btn-outline-dark">Delete</a></div>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}