TripLog/Models/TripViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.AspNetCore.Mvc.Rendering;
using TripLogDaAL.Entities;

namespace TripLog.Models
{
    public class TripViewModel
    {
        public OldTrip OldTrip { get; set; }
        public int PageNumber { get; set; }
        public Trip trip { get; set; }
        public List<Destination> Destinations { get; set; }
        public List<Accommodation> Accommodations { get; set; }
        public List<Activity> Activities { get; set; }
        public  string SelectedDestinationName { get; set; }
    }
}

TripLog/Controllers/AccommodationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TripLog.Models;
using TripLogDaAL.DAL;
using TripLogDaAL.DBContext;
using TripLogDaAL.Entities;

namespace TripLog.Controllers
{
    public class AccommodationController : Controller
    {
        public readonly TripDbContext _context;
        public AccommodationController(TripDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string errormessage = "")
        {
            TripDAL dal = new TripDAL(_context);
            var allAccommodations = dal.GetAllAccommodations();
            AccommodationViewModel vm = new AccommodationViewModel();
            vm.Accommodations = allAccommodations;
            if (allAccommodations != null && allAccommodations.Any())
            {
                vm.SelectedAccommodationId = allAccommodations[0].AccommodationId;
                vm.SelectedAccommodationName = allAccommodations[0].AccommodationName;
            }

            TempData["message"] = errormessage;
            return View(vm);
        }

        public IActionResult AddAccommodation(string NewAccommodationName, string NewAccommodationPhone,string NewAccommodationEmail)
        {
            string error = string.Empty;
            if (string.IsNullOrEmpty(NewAccommodationName))
            {
                error = "Enter Accommodation Name";

                return RedirectToAction("Index", new { errorMessage = error });
            }
            TripDAL dal = new TripDAL(_context);
            var allAccommodations = dal.GetAllAccommodations();
            if (allAccommodations != null && allAccommodations.Any())
            {
                if (allAccommodations.Any(x => x.AccommodationName.ToLower() == NewAccommodationName.ToLower()))
                {
                    error = "Accommodation Name already exists";
                    return RedirectToAction("Index", new { errorMessage = error });
                }
            }

            Accommodation newAccommodation = new Accommodation() {  AccommodationName = NewAccommodationName,AccommodationEmail =  NewAccommodationEmail, AccommodationPhone = NewAccommodationPhone};
            bool success = dal.AddAccommodation(newAccommodation);
            if (success)
            {
                TempData["message"] = $"Acommodation - {NewAccommodationName} added successfully";
                return RedirectToAction("Add", "Trip");
            }
            else
            {
                error = $"DBError : Cannot create new Accommodation - {NewAccommodationName}. Please try again";
                return RedirectToAction("Index", new { errorMessage = error });
            }
        }

        public IActionResult DeleteAccommodation(int SelectedAccommodationId, string SelectedAccommodationName)
        {
            string error = string.Empty;
            TripDAL dal = new TripDAL(_context);
            bool success = dal.DeleteAccommodation(SelectedAccommodationId);
            if (success)
            {
                TempData["message"] = $"Accommodation  {SelectedAccommodationName} deleted successfully";
                return RedirectToAction("Add", "Trip");

            }
            else
            {
                error = "DBError : Cannot delete Accommodation - {SelectedAccommodationName}";
                return RedirectToAction("Index", new { errorMessage = error });
            }

        }
    }
}

TripLog/Controllers/ActivityController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TripLog.Models;
using TripLogDaAL.DAL;
using TripLogDaAL.DBContext;
using TripLogDaAL.Entities;

namespace TripLog.Controllers
{
    public class ActivityController : Controller
    {
        public readonly TripDbContext _context;
        public ActivityController(TripDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string errormessage = "")
        {
            TripDAL dal = new TripDAL(_context);
            var allActivities = dal.GetAllActivity();
            var activity = new Activity();
            ActivityViewModel vm = new ActivityViewModel();
            vm.Activities = allActivities;
            if (allActivities != null && allActivities.Any())
            {
                vm.SelectedActivityId = allActivities[0].ActivityId;
                vm.SelectedActivityName = allActivities[0].ActivityName;
            }

            TempData["message"] = errormessage;
            return View(vm);
        }

        public IActionResult AddActivity(string NewActivityName)
        {
            string error = string.Empty;
            if (string.IsNullOrEmpty(NewActivityName))
            {
                error = "Enter Activity Name";

                return RedirectToAction("Index", new { errorMessage = error });
            }
            TripDAL dal = new TripDAL(_context);
            var allActivities = dal.GetAllActivity();
            if (allActivities != null && allActivities.Any())
            {
                if (allActivities.Any(x => x.ActivityName.ToLower() == NewActivityName.ToLower()))
                {
                    error = "Activity Name already exists";
                    return RedirectToAction("Index", new { errorMessage = error });
                }
            }

            Activity newActivity = new Activity() {  ActivityName = NewActivityName};
            bool success = dal.AddActvity(newActivity);
            if (success)
            {
                TempData["message"] = $"Activity - {NewActivityName} added successfully";
                return RedirectToAction("Add", "Trip");
            }
            else
            {
                error = $"DBError : Cannot create new Activity - {NewActivityName}. Please try again";
                return RedirectToAction("Index", new { errorMessage = error });
            }
        }

        public IActionResult DeleteActivity(int SelectedActivityId, string SelectedActivityName)
        {
            string error = string.Empty;
            TripDAL dal = new TripDAL(_context);
            bool success = dal.DeleteActivity(SelectedActivityId);
            if (success)
            {
                TempData["message"] = $"Activity-   {SelectedActivityName} deleted successfully";
                return RedirectToAction("Add", "Trip");

            }
            else
            {
                error = $"DBError : Cannot delete Activity - {SelectedActivityName}.";
                return RedirectToAction("Index", new { errorMessage = error });
            }

        }
    }
}

TripLog/Controllers/DestinationController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using TripLog.Models;
using TripLogDaAL.DAL;
using TripLogDaAL.DBContext;
using TripLogDaAL.Entities;

namespace TripLog.Controllers
{
    public class DestinationController : Controller
    {
        public readonly TripDbContext _context;
        public DestinationController(TripDbContext context)
        {
            _context = context;
        }
        public IActionResult Index(string errormessage = "")
        {
            TripDAL dal = new TripDAL(_context);
            var allDestinations = dal.GetAllDestinations();
            var newDestination = new Destination();
            DestinationViewModel vm = new DestinationViewModel();
            vm.Destinations = allDestinations;
            if (allDestinations != null && allDestinations.Any())
            {
                vm.SelectedDestinationId = allDestinations[0].DestinationId;
                vm.SelectedDestinationName = allDestinations[0].DestinationName;
            }

            TempData["message"] = errormessage;
            return View(vm);
        }

        public IActionResult AddDestination(string NewDestinationName)
        {
            string error = string.Empty;
            if (string.IsNullOrEmpty(NewDestinationName))
            {
                error = "Enter Destination Name";

                return RedirectToAction("Index", new { errorMessage = error });
            }
            TripDAL dal = new TripDAL(_context);
            var allDestinations = dal.GetAllDestinations();
            if (allDestinations != null && allDestinations.Any())
            {
                if (allDestinations.Any(x => x.DestinationName.ToLower() == NewDestinationName.ToLower()))
                {
                    error = "Destination Name already exists";
                    return RedirectToAction("Index", new { errorMessage = error });
                }
            }

            Destination newDest = new Destination() { DestinationName = NewDestinationName };
            bool success = dal.AddDestination(newDest);
            if (success)
            {
                TempData["message"] = $"Destination - {NewDestinationName} added successfully";
                return RedirectToAction("Add", "Trip");
            }
            else
            {
                error = "DBError : Cannot create new destination. Please try again";
                return RedirectToAction("Index", new { errorMessage = error });
            }
        }
        
        public IActionResult DeleteDestination(int SelectedDestinationId, string SelectedDestinationName)
        {
            string error = string.Empty;
            TripDAL dal = new TripDAL(_context);
            bool success = dal.DeleteDestination(SelectedDestinationId);
            if (success)
            {
                TempData["message"] = $"Destination  {SelectedDestinationName} deleted successfully";
                return RedirectToAction("Add", "Trip");
                
            }
            else
            {
                error = "DBError : Cannot delete destination. Make sure no trips are mapped against selected destination";
                return RedirectToAction("Index", new { errorMessage = error });
            }
            
        }
    }
}

TripLog/Controllers/TripController.cs
using System;
using System.Runtime.InteropServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.Internal;
using TripLog.Models;
using TripLogDaAL.DAL;
using TripLogDaAL.DBContext;
using TripLogDaAL.Entities;

namespace TripLog.Controllers
{
    public class TripController : Controller
    {
        private readonly TripDbContext _context;
        public TripController(TripDbContext context)
        {
            _context = context;
        }
        public RedirectToActionResult Index() => RedirectToAction("Index", "Home");

        [HttpGet]
        public ViewResult Add(string id = "")
        {
            var vm = new TripViewModel();
            TripDAL dal = new TripDAL(_context);
            vm.Destinations = dal.GetAllDestinations();
            vm.Accommodations = dal.GetAllAccommodations();
            vm.Activities = dal.GetAllActivity();   
            /********************************************************************************************
            * need to pass Accommodation value, or Destination value (depending on page number and 
            * Accommodation value), to by view. 
            * 
            * Accommodation is an optional value - don't need it to persist after being read if it's null.
            * So, do straight read, and if it's not null, use Keep() method to make sure it persists.
            * 
            * Destination is a a required value - always need it to persist after being read. 
            * So, use Peek() method to read it and make sure it persists.
            *********************************************************************************************/
               
            if (id.ToLower() == "page3")
            {
                vm.PageNumber = 3;
                vm.trip = new Trip
                {
                    DestinationId = (int)TempData.Peek(nameof(Trip.DestinationId)),
                    AccommodationId = (int)TempData.Peek(nameof(Trip.AccommodationId)),
                    StartDate = (DateTime)TempData.Peek(nameof(Trip.StartDate)),
                    EndDate = (DateTime)TempData.Peek(nameof(Trip.EndDate)),
                };
                vm.SelectedDestinationName = TempData.Peek(nameof(TripViewModel.SelectedDestinationName)).ToString();
                return View("Add3", vm);
            }
            else 
            {
                vm.PageNumber = 1;
                if (vm.Destinations != null && vm.Destinations.Any())
                {
                    vm.SelectedDestinationName = vm.Destinations[0].DestinationName;
                }
                return View("Add1", vm);
            }      
        }
            
        [HttpPost]
        public IActionResult Add(TripViewModel vm)
        {
            TripDAL dal = new TripDAL(_context);
            if (vm.PageNumber == 1)
            {
                if (ModelState.IsValid) // only page 1 has required data
                {
                    /***************************************************
                    * Store data in TempData and redirect (PRG pattern)
                    ****************************************************/
                    TempData[nameof(Trip.AccommodationId)] = vm.trip.AccommodationId;
                    TempData[nameof(Trip.DestinationId)] = vm.trip.DestinationId;
                    TempData[nameof(Trip.StartDate)] = vm.trip.StartDate;
                    TempData[nameof(Trip.EndDate)] = vm.trip.EndDate;
                    var selectedItem = dal.GetAllDestinations().Find(p => p.DestinationId == vm.trip.DestinationId);
                    TempData[nameof(TripViewModel.SelectedDestinationName)] = selectedItem?.DestinationName;
                    
                    return RedirectToAction("Add", new { id = "Page3" });
                }
                else
                {
                    TempData["message"] = "Enter Valid inputs";
                    return RedirectToAction("Add");
                }
            }
            else if (vm.PageNumber == 3)
            {
                /***************************************************
                    *  Store data in TempData and redirect (PRG pattern)
                ****************************************************/
                

                if (vm.trip != null)
                {
                    bool success = dal.AddTrip(vm.trip);
                    if (success)
                    {
                        TempData["message"] = $"The Following Trip to {TempData.Peek(nameof(TripViewModel.SelectedDestinationName))} has been added.";
                    }
                    else
                    {
                        TempData["message"] = $"Database Error : The Following Trip to {TempData.Peek(nameof(TripViewModel.SelectedDestinationName)).ToString()} has been added.";
                    }
                }
                else
                {
                    TempData["message"] = $"Failed to add trip : {TempData.Peek(nameof(TripViewModel.SelectedDestinationName)).ToString()}";
                }
                
                
           
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Index", "Home");
            }

        }

        public RedirectToActionResult Cancel()
        {
            TempData.Clear();
            return RedirectToAction("Index", "Home");
        }
    }
}

TripLog/Views/Trip/Add1.cshtml
@model TripViewModel

@{
    ViewBag.Title = "Add Trip";
    ViewBag.SubHeader = "Add Trip Destination and Dates";
}

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-action="Add">
    <input type="hidden" asp-for="PageNumber" />

    <div class="form-group">
        <label asp-for="Destinations">Destination</label>&nbsp;&nbsp;<a asp-action="Index" asp-controller="Destination">Manage Destinations</a>
        
        @if (Model.Destinations != null && Model.Destinations.Any())
        {
            @Html.DropDownListFor(model => model.trip.DestinationId, new SelectList(Model.Destinations, "DestinationId", "DestinationName"), new {@id = "ddlDestination", @class = "form-control"})
            @Html.HiddenFor(model => model.SelectedDestinationName, new {@id = "hdnDestinationName"})
        }
        else
        {
            @Html.DropDownList("Destination", Enumerable.Empty<SelectListItem>(), new {@disabled = "disabled",@class = "form-control" })
        }

    </div>

    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
    <script type="text/javascript">
        $("body").on("change", "#ddlDestination", function () {
            $("#hdnDestinationName").val($(this).find("option:selected").text());
        });
    </script>
    <div class="form-group">
        <label asp-for="trip.Accommodation">Accommodations</label>&nbsp;&nbsp;<a asp-action="Index" asp-controller="Accommodation">Manage Accommodations</a>
    @if (Model.Accommodations != null && Model.Accommodations.Any())
    {

        @Html.DropDownListFor(model => model.trip.AccommodationId, new SelectList(Model.Accommodations, "AccommodationId", "AccommodationName"), new {@class = "form-control"})
    }
    else
    {
        @Html.DropDownList("Accommodation", Enumerable.Empty<SelectListItem>(), new {@disabled = "disabled", @class = "form-control" })
    }
    </div>

    <div class="form-group">
        <label asp-for="trip.StartDate">Start Date</label>
        <input type="date" asp-for="trip.StartDate" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="trip.EndDate">End Date</label>
        <input type="date" asp-for="trip.EndDate" class="form-control" />
    </div>
    <div>
        @if (Model.Destinations != null && Model.Destinations.Any() && Model.Accommodations != null && Model.Accommodations.Any())
        {
            <button type="submit" class="btn btn-dark">Next</button>
        }
        else
        {
            <button class="btn btn-dark" disabled="disabled" >Next</button>
        }
        <a asp-action="Cancel" class="btn btn-outline-dark">Cancel</a>
    </div>
</form>

TripLog/Views/Trip/Add2.cshtml
@model TripViewModel

@{
    ViewBag.Title = "Add OldTrip - Page 2";
    ViewBag.SubHeader = $"Add Info for {Model.OldTrip.Accommodation}";
}

<form asp-action="Add">
    <input type="hidden" asp-for="PageNumber" />

    <div class="form-group">
        <label asp-for="OldTrip.AccommodationPhone">Phone Number</label>
        <input asp-for="OldTrip.AccommodationPhone" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="OldTrip.AccommodationEmail">Email Address</label>
        <input asp-for="OldTrip.AccommodationEmail" class="form-control" />
    </div>

    <div>
        <button type="submit" class="btn btn-dark">Next</button>
        <a asp-action="Cancel" class="btn btn-outline-dark">Cancel</a>
    </div>
</form>

TripLog/Views/Trip/Add3.cshtml
@using TripLogDaAL.Entities
@model TripViewModel

@{
    ViewBag.Title = "Add Activities";
    ViewBag.SubHeader = $"Add Things To Do in {Model.trip.DestinationId}";
}

<form asp-action="Add">
    <input type="hidden" asp-for="PageNumber" />
    <input type="hidden" asp-for="trip.DestinationId" />
    <input type="hidden" asp-for="trip.AccommodationId" />
    <input type="hidden" asp-for="trip.StartDate" />
    <input type="hidden" asp-for="trip.EndDate" />
    <input type="hidden" asp-for="SelectedDestinationName" />
    
    <div class="form-control">
        <a asp-action="Index" asp-controller="Activity">Manage Activities</a>
    </div>
    <div class="form-group">
        @Html.ListBoxFor(x => x.trip.SelectedActivities, new SelectList(Model.Activities, "ActivityId", "ActivityName"), new { @class = "form-control" });
    </div>


    <div>
        <button type="submit" class="btn btn-dark">Save</button>
        <a asp-action="Cancel" class="btn btn-outline-dark">Cancel</a>
    </div>
</form>